import java.util.*;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
    private ItemRepository itemRepository;
    private SalesPromotionRepository salesPromotionRepository;

    public App(ItemRepository itemRepository, SalesPromotionRepository salesPromotionRepository) {
        this.itemRepository = itemRepository;
        this.salesPromotionRepository = salesPromotionRepository;
    }

    public String bestCharge(List<String> inputs) {
        //TODO: write code here
        //"ITEM0001 x 1", "ITEMi0013 x 2", "ITEM0022 x 1")
        if(inputs.size()<1){
            return "";
        }
        List<Item> itemList = itemRepository.findAll();//菜信息
        List<SalesPromotion> salesPromotionList = salesPromotionRepository.findAll();//折扣信息
        Map<String,Boolean> SaleMap = new HashMap<>();//优惠菜
        for(String itemName : salesPromotionList.get(1).getRelatedItems()){
            SaleMap.put(itemName,true);
        }
        String s="============= 订餐明细 =============\n" +
                "黄焖鸡 x 1 = 18元\n" +
                "肉夹馍 x 2 = 12元\n" +
                "凉皮 x 1 = 8元\n" +
                "-----------------------------------\n" +
                "使用优惠:\n" +
                "指定菜品半价(黄焖鸡，凉皮)，省13元\n" +
                "-----------------------------------\n" +
                "总计：25元\n" +
                "===================================";
        StringBuffer out = new StringBuffer();//输入信息
        Double pay = 0d;//总价
        Double discount = 0d;//优惠金额
        List<String> discountItemList = new ArrayList<>();
        out.append("============= 订餐明细 =============\n");
        for(String input:inputs){
            List<String> words = Arrays.asList(input.split(" "));
            for(Item item : itemList){
                if(words.get(0).equals(item.getId())){
                    Double total = item.getPrice() * Integer.parseInt(words.get(2)); //单样菜总额
                    pay +=total;//更新总价
                    if(SaleMap.get(words.get(0))){ //如果是折扣菜
                       discount += (item.getPrice()/2)*Integer.parseInt(words.get(2));//记录优惠金额
                        discountItemList.add(item.getName());//存储折扣菜单
                    }
                    out.append(String.format("{0} x {1} = {2}元", item.getName(), words.get(2),(int)total.doubleValue()));
                    break;
                }
            }
            out.append("-----------------------------------\n"+
                    "使用优惠:\n");
            if((pay>=30d&&discount>6d)||(pay<30d&&discount!=0d)){
                out.append(String.format("指定菜品半价({0})，省{1}元\n",String.join(",",discountItemList),(int)discount.doubleValue()));
                out.append("-----------------------------------\n");
            }else if(pay>30&&discount<=6){
                out.append("满30减6元，省6元");
                out.append("-----------------------------------\n");
            }
            out.append("总计：+"+(int)pay.doubleValue()+"元\n" +
                    "===================================");
        }
        return out.toString();
    }
}
